// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#include "com/ezored/holiday/HolidayFeriado.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

HolidayFeriado::HolidayFeriado() = default;

HolidayFeriado::~HolidayFeriado() = default;

auto HolidayFeriado::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<HolidayFeriado>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.siglaPais)),
                                                           ::djinni::get(::djinni::Date::fromCpp(jniEnv, c.data)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.nome)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto HolidayFeriado::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<HolidayFeriado>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mSiglaPais)),
            ::djinni::Date::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mData)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mNome))};
}

}  // namespace djinni_generated
