// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni_support.hpp"
#include "ezored/holiday/Feriado.hpp"

namespace djinni_generated {

class HolidayFeriado final {
public:
    using CppType = ::ezored::holiday::Feriado;
    using JniType = jobject;

    using Boxed = HolidayFeriado;

    ~HolidayFeriado();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    HolidayFeriado();
    friend ::djinni::JniClass<HolidayFeriado>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/ezored/holiday/Feriado") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/util/Date;Ljava/lang/String;)V") };
    const jfieldID field_mSiglaPais { ::djinni::jniGetFieldID(clazz.get(), "mSiglaPais", "Ljava/lang/String;") };
    const jfieldID field_mData { ::djinni::jniGetFieldID(clazz.get(), "mData", "Ljava/util/Date;") };
    const jfieldID field_mNome { ::djinni::jniGetFieldID(clazz.get(), "mNome", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
