// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#include "com/ezored/holiday/HolidayPais.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

HolidayPais::HolidayPais() = default;

HolidayPais::~HolidayPais() = default;

auto HolidayPais::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<HolidayPais>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.sigla)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.nome)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto HolidayPais::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<HolidayPais>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mSigla)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mNome))};
}

}  // namespace djinni_generated
