// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#include "com/ezored/holiday/HolidaySincronizacao.hpp"  // my header
#include "com/ezored/holiday/HolidaySincronizacaoListener.hpp"

namespace djinni_generated {

HolidaySincronizacao::HolidaySincronizacao() : ::djinni::JniInterface<::ezored::holiday::Sincronizacao, HolidaySincronizacao>("com/ezored/holiday/Sincronizacao$CppProxy") {}

HolidaySincronizacao::~HolidaySincronizacao() = default;


CJNIEXPORT void JNICALL Java_com_ezored_holiday_Sincronizacao_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ezored::holiday::Sincronizacao>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_ezored_holiday_Sincronizacao_00024CppProxy_baixarTudo(JNIEnv* jniEnv, jobject /*this*/, jobject j_listener)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        ::ezored::holiday::Sincronizacao::baixarTudo(::djinni_generated::HolidaySincronizacaoListener::toCpp(jniEnv, j_listener));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
