// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni_support.hpp"
#include "ezored/holiday/SincronizacaoListener.hpp"

namespace djinni_generated {

class HolidaySincronizacaoListener final : ::djinni::JniInterface<::ezored::holiday::SincronizacaoListener, HolidaySincronizacaoListener> {
public:
    using CppType = std::shared_ptr<::ezored::holiday::SincronizacaoListener>;
    using CppOptType = std::shared_ptr<::ezored::holiday::SincronizacaoListener>;
    using JniType = jobject;

    using Boxed = HolidaySincronizacaoListener;

    ~HolidaySincronizacaoListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<HolidaySincronizacaoListener>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<HolidaySincronizacaoListener>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    HolidaySincronizacaoListener();
    friend ::djinni::JniClass<HolidaySincronizacaoListener>;
    friend ::djinni::JniInterface<::ezored::holiday::SincronizacaoListener, HolidaySincronizacaoListener>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::ezored::holiday::SincronizacaoListener
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void sucesso() override;
        void falha(const std::string & mensagem) override;

    private:
        friend ::djinni::JniInterface<::ezored::holiday::SincronizacaoListener, ::djinni_generated::HolidaySincronizacaoListener>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/ezored/holiday/SincronizacaoListener") };
    const jmethodID method_sucesso { ::djinni::jniGetMethodID(clazz.get(), "sucesso", "()V") };
    const jmethodID method_falha { ::djinni::jniGetMethodID(clazz.get(), "falha", "(Ljava/lang/String;)V") };
};

}  // namespace djinni_generated
