// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni_support.hpp"
#include "ezored/holiday/PaisRepository.hpp"

namespace djinni_generated {

class HolidayPaisRepository final : ::djinni::JniInterface<::ezored::holiday::PaisRepository, HolidayPaisRepository> {
public:
    using CppType = std::shared_ptr<::ezored::holiday::PaisRepository>;
    using CppOptType = std::shared_ptr<::ezored::holiday::PaisRepository>;
    using JniType = jobject;

    using Boxed = HolidayPaisRepository;

    ~HolidayPaisRepository();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<HolidayPaisRepository>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<HolidayPaisRepository>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    HolidayPaisRepository();
    friend ::djinni::JniClass<HolidayPaisRepository>;
    friend ::djinni::JniInterface<::ezored::holiday::PaisRepository, HolidayPaisRepository>;

};

}  // namespace djinni_generated
