// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni_support.hpp"
#include "ezored/holiday/Pais.hpp"

namespace djinni_generated {

class HolidayPais final {
public:
    using CppType = ::ezored::holiday::Pais;
    using JniType = jobject;

    using Boxed = HolidayPais;

    ~HolidayPais();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    HolidayPais();
    friend ::djinni::JniClass<HolidayPais>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/ezored/holiday/Pais") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mSigla { ::djinni::jniGetFieldID(clazz.get(), "mSigla", "Ljava/lang/String;") };
    const jfieldID field_mNome { ::djinni::jniGetFieldID(clazz.get(), "mNome", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
