// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni_support.hpp"
#include "ezored/holiday/FeriadoRepository.hpp"

namespace djinni_generated {

class HolidayFeriadoRepository final : ::djinni::JniInterface<::ezored::holiday::FeriadoRepository, HolidayFeriadoRepository> {
public:
    using CppType = std::shared_ptr<::ezored::holiday::FeriadoRepository>;
    using CppOptType = std::shared_ptr<::ezored::holiday::FeriadoRepository>;
    using JniType = jobject;

    using Boxed = HolidayFeriadoRepository;

    ~HolidayFeriadoRepository();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<HolidayFeriadoRepository>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<HolidayFeriadoRepository>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    HolidayFeriadoRepository();
    friend ::djinni::JniClass<HolidayFeriadoRepository>;
    friend ::djinni::JniInterface<::ezored::holiday::FeriadoRepository, HolidayFeriadoRepository>;

};

}  // namespace djinni_generated
