// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#include "com/ezored/holiday/HolidayFeriadoRepository.hpp"  // my header
#include "Marshal.hpp"
#include "com/ezored/holiday/HolidayFeriado.hpp"

namespace djinni_generated {

HolidayFeriadoRepository::HolidayFeriadoRepository() : ::djinni::JniInterface<::ezored::holiday::FeriadoRepository, HolidayFeriadoRepository>("com/ezored/holiday/FeriadoRepository$CppProxy") {}

HolidayFeriadoRepository::~HolidayFeriadoRepository() = default;


CJNIEXPORT void JNICALL Java_com_ezored_holiday_FeriadoRepository_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ezored::holiday::FeriadoRepository>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_ezored_holiday_FeriadoRepository_00024CppProxy_findAll(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ezored::holiday::FeriadoRepository::findAll();
        return ::djinni::release(::djinni::List<::djinni_generated::HolidayFeriado>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_ezored_holiday_FeriadoRepository_00024CppProxy_findByPais(JNIEnv* jniEnv, jobject /*this*/, jstring j_siglaPais)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ezored::holiday::FeriadoRepository::findByPais(::djinni::String::toCpp(jniEnv, j_siglaPais));
        return ::djinni::release(::djinni::List<::djinni_generated::HolidayFeriado>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
