// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include <chrono>
#include <string>
#include <utility>

namespace ezored { namespace holiday {

struct Feriado final {
    std::string siglaPais;
    std::chrono::system_clock::time_point data;
    std::string nome;

    Feriado(std::string siglaPais_,
            std::chrono::system_clock::time_point data_,
            std::string nome_)
    : siglaPais(std::move(siglaPais_))
    , data(std::move(data_))
    , nome(std::move(nome_))
    {}
};

} }  // namespace ezored::holiday
