// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include <string>
#include <vector>

namespace ezored { namespace holiday {

struct Feriado;

class FeriadoRepository {
public:
    virtual ~FeriadoRepository() {}

    static std::vector<Feriado> findAll();

    static std::vector<Feriado> findByPais(const std::string & siglaPais);
};

} }  // namespace ezored::holiday
