// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include <string>
#include <utility>

namespace ezored { namespace holiday {

struct Pais final {
    std::string sigla;
    std::string nome;

    Pais(std::string sigla_,
         std::string nome_)
    : sigla(std::move(sigla_))
    , nome(std::move(nome_))
    {}
};

} }  // namespace ezored::holiday
