// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include <string>
#include <vector>

namespace ezored { namespace holiday {

struct Pais;

class PaisRepository {
public:
    virtual ~PaisRepository() {}

    static std::vector<Pais> findAll();

    static Pais getBySigla(const std::string & siglaPais);
};

} }  // namespace ezored::holiday
