// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include <memory>

namespace ezored { namespace holiday {

class SincronizacaoListener;

class Sincronizacao {
public:
    virtual ~Sincronizacao() {}

    static void baixarTudo(const std::shared_ptr<SincronizacaoListener> & listener);
};

} }  // namespace ezored::holiday
