// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include <string>

namespace ezored { namespace holiday {

class SincronizacaoListener {
public:
    virtual ~SincronizacaoListener() {}

    virtual void sucesso() = 0;

    virtual void falha(const std::string & mensagem) = 0;
};

} }  // namespace ezored::holiday
