// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

@interface HolidayFeriado : NSObject
- (nonnull instancetype)initWithSiglaPais:(nonnull NSString *)siglaPais
                                     data:(nonnull NSDate *)data
                                     nome:(nonnull NSString *)nome;
+ (nonnull instancetype)feriadoWithSiglaPais:(nonnull NSString *)siglaPais
                                        data:(nonnull NSDate *)data
                                        nome:(nonnull NSString *)nome;

@property (nonatomic, readonly, nonnull) NSString * siglaPais;

@property (nonatomic, readonly, nonnull) NSDate * data;

@property (nonatomic, readonly, nonnull) NSString * nome;

@end
