// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/holiday/HolidayFeriadoRepository+Private.h"
#import "ezored/holiday/HolidayFeriadoRepository.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "ezored/holiday/HolidayFeriado+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface HolidayFeriadoRepository ()

- (id)initWithCpp:(const std::shared_ptr<::ezored::holiday::FeriadoRepository>&)cppRef;

@end

@implementation HolidayFeriadoRepository {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ezored::holiday::FeriadoRepository>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ezored::holiday::FeriadoRepository>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nonnull NSArray<HolidayFeriado *> *)findAll {
    try {
        auto objcpp_result_ = ::ezored::holiday::FeriadoRepository::findAll();
        return ::djinni::List<::djinni_generated::Feriado>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nonnull NSArray<HolidayFeriado *> *)findByPais:(nonnull NSString *)siglaPais {
    try {
        auto objcpp_result_ = ::ezored::holiday::FeriadoRepository::findByPais(::djinni::String::toCpp(siglaPais));
        return ::djinni::List<::djinni_generated::Feriado>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto FeriadoRepository::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto FeriadoRepository::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<HolidayFeriadoRepository>(cpp);
}

}  // namespace djinni_generated

@end
