// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/holiday/HolidayPaisRepository+Private.h"
#import "ezored/holiday/HolidayPaisRepository.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "ezored/holiday/HolidayPais+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface HolidayPaisRepository ()

- (id)initWithCpp:(const std::shared_ptr<::ezored::holiday::PaisRepository>&)cppRef;

@end

@implementation HolidayPaisRepository {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ezored::holiday::PaisRepository>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ezored::holiday::PaisRepository>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nonnull NSArray<HolidayPais *> *)findAll {
    try {
        auto objcpp_result_ = ::ezored::holiday::PaisRepository::findAll();
        return ::djinni::List<::djinni_generated::Pais>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nonnull HolidayPais *)getBySigla:(nonnull NSString *)siglaPais {
    try {
        auto objcpp_result_ = ::ezored::holiday::PaisRepository::getBySigla(::djinni::String::toCpp(siglaPais));
        return ::djinni_generated::Pais::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto PaisRepository::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto PaisRepository::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<HolidayPaisRepository>(cpp);
}

}  // namespace djinni_generated

@end
