// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/holiday/HolidayFeriado+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Feriado::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.siglaPais),
            ::djinni::Date::toCpp(obj.data),
            ::djinni::String::toCpp(obj.nome)};
}

auto Feriado::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[HolidayFeriado alloc] initWithSiglaPais:(::djinni::String::fromCpp(cpp.siglaPais))
                                                data:(::djinni::Date::fromCpp(cpp.data))
                                                nome:(::djinni::String::fromCpp(cpp.nome))];
}

}  // namespace djinni_generated
