// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/holiday/HolidaySincronizacao+Private.h"
#import "ezored/holiday/HolidaySincronizacao.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "ezored/holiday/HolidaySincronizacaoListener+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface HolidaySincronizacao ()

- (id)initWithCpp:(const std::shared_ptr<::ezored::holiday::Sincronizacao>&)cppRef;

@end

@implementation HolidaySincronizacao {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ezored::holiday::Sincronizacao>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ezored::holiday::Sincronizacao>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (void)baixarTudo:(nullable id<HolidaySincronizacaoListener>)listener {
    try {
        ::ezored::holiday::Sincronizacao::baixarTudo(::djinni_generated::SincronizacaoListener::toCpp(listener));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Sincronizacao::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Sincronizacao::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<HolidaySincronizacao>(cpp);
}

}  // namespace djinni_generated

@end
