// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#include "ezored/holiday/Sincronizacao.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HolidaySincronizacao;

namespace djinni_generated {

class Sincronizacao
{
public:
    using CppType = std::shared_ptr<::ezored::holiday::Sincronizacao>;
    using CppOptType = std::shared_ptr<::ezored::holiday::Sincronizacao>;
    using ObjcType = HolidaySincronizacao*;

    using Boxed = Sincronizacao;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

