// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/holiday/HolidayFeriado.h"
#include "ezored/holiday/Feriado.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HolidayFeriado;

namespace djinni_generated {

struct Feriado
{
    using CppType = ::ezored::holiday::Feriado;
    using ObjcType = HolidayFeriado*;

    using Boxed = Feriado;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
