// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/holiday/HolidayPais.h"
#import <Foundation/Foundation.h>


@interface HolidayPaisRepository : NSObject

+ (nonnull NSArray<HolidayPais *> *)findAll;

+ (nonnull HolidayPais *)getBySigla:(nonnull NSString *)siglaPais;

@end
