// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/holiday/HolidayPais+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Pais::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.sigla),
            ::djinni::String::toCpp(obj.nome)};
}

auto Pais::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[HolidayPais alloc] initWithSigla:(::djinni::String::fromCpp(cpp.sigla))
                                         nome:(::djinni::String::fromCpp(cpp.nome))];
}

}  // namespace djinni_generated
