// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/holiday/HolidayFeriado.h"
#import <Foundation/Foundation.h>


@interface HolidayFeriadoRepository : NSObject

+ (nonnull NSArray<HolidayFeriado *> *)findAll;

+ (nonnull NSArray<HolidayFeriado *> *)findByPais:(nonnull NSString *)siglaPais;

@end
