// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

@interface HolidayPais : NSObject
- (nonnull instancetype)initWithSigla:(nonnull NSString *)sigla
                                 nome:(nonnull NSString *)nome;
+ (nonnull instancetype)paisWithSigla:(nonnull NSString *)sigla
                                 nome:(nonnull NSString *)nome;

@property (nonatomic, readonly, nonnull) NSString * sigla;

@property (nonatomic, readonly, nonnull) NSString * nome;

@end
