// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/holiday/HolidayPais.h"
#include "ezored/holiday/Pais.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HolidayPais;

namespace djinni_generated {

struct Pais
{
    using CppType = ::ezored::holiday::Pais;
    using ObjcType = HolidayPais*;

    using Boxed = Pais;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
