// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/holiday/HolidayFeriado.h"


@implementation HolidayFeriado

- (nonnull instancetype)initWithSiglaPais:(nonnull NSString *)siglaPais
                                     data:(nonnull NSDate *)data
                                     nome:(nonnull NSString *)nome
{
    if (self = [super init]) {
        _siglaPais = [siglaPais copy];
        _data = data;
        _nome = [nome copy];
    }
    return self;
}

+ (nonnull instancetype)feriadoWithSiglaPais:(nonnull NSString *)siglaPais
                                        data:(nonnull NSDate *)data
                                        nome:(nonnull NSString *)nome
{
    return [(HolidayFeriado*)[self alloc] initWithSiglaPais:siglaPais
                                                       data:data
                                                       nome:nome];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p siglaPais:%@ data:%@ nome:%@>", self.class, (void *)self, self.siglaPais, self.data, self.nome];
}

@end
