// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>


@protocol HolidaySincronizacaoListener

- (void)sucesso;

- (void)falha:(nonnull NSString *)mensagem;

@end
