// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/holiday/HolidaySincronizacaoListener+Private.h"
#import "ezored/holiday/HolidaySincronizacaoListener.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class SincronizacaoListener::ObjcProxy final
: public ::ezored::holiday::SincronizacaoListener
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::SincronizacaoListener;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void sucesso() override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() sucesso];
        }
    }
    void falha(const std::string & c_mensagem) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() falha:(::djinni::String::fromCpp(c_mensagem))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto SincronizacaoListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto SincronizacaoListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
