// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#include "ezored/holiday/FeriadoRepository.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HolidayFeriadoRepository;

namespace djinni_generated {

class FeriadoRepository
{
public:
    using CppType = std::shared_ptr<::ezored::holiday::FeriadoRepository>;
    using CppOptType = std::shared_ptr<::ezored::holiday::FeriadoRepository>;
    using ObjcType = HolidayFeriadoRepository*;

    using Boxed = FeriadoRepository;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

