// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#include "ezored/holiday/SincronizacaoListener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol HolidaySincronizacaoListener;

namespace djinni_generated {

class SincronizacaoListener
{
public:
    using CppType = std::shared_ptr<::ezored::holiday::SincronizacaoListener>;
    using CppOptType = std::shared_ptr<::ezored::holiday::SincronizacaoListener>;
    using ObjcType = id<HolidaySincronizacaoListener>;

    using Boxed = SincronizacaoListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

