// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>
@protocol HolidaySincronizacaoListener;


@interface HolidaySincronizacao : NSObject

+ (void)baixarTudo:(nullable id<HolidaySincronizacaoListener>)listener;

@end
