// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/holiday/HolidayPais.h"


@implementation HolidayPais

- (nonnull instancetype)initWithSigla:(nonnull NSString *)sigla
                                 nome:(nonnull NSString *)nome
{
    if (self = [super init]) {
        _sigla = [sigla copy];
        _nome = [nome copy];
    }
    return self;
}

+ (nonnull instancetype)paisWithSigla:(nonnull NSString *)sigla
                                 nome:(nonnull NSString *)nome
{
    return [(HolidayPais*)[self alloc] initWithSigla:sigla
                                                nome:nome];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p sigla:%@ nome:%@>", self.class, (void *)self, self.sigla, self.nome];
}

@end
