// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

package com.ezored.holiday;

import java.util.Date;

public final class Feriado {


    /*package*/ final String mSiglaPais;

    /*package*/ final Date mData;

    /*package*/ final String mNome;

    public Feriado(
            String siglaPais,
            Date data,
            String nome) {
        this.mSiglaPais = siglaPais;
        this.mData = data;
        this.mNome = nome;
    }

    public String getSiglaPais() {
        return mSiglaPais;
    }

    public Date getData() {
        return mData;
    }

    public String getNome() {
        return mNome;
    }

    @Override
    public String toString() {
        return "Feriado{" +
                "mSiglaPais=" + mSiglaPais +
                "," + "mData=" + mData +
                "," + "mNome=" + mNome +
        "}";
    }

}
