// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

package com.ezored.holiday;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class FeriadoRepository {
    public static ArrayList<Feriado> findAll()
    {
        return CppProxy.findAll();
    }

    public static ArrayList<Feriado> findByPais(String siglaPais)
    {
        return CppProxy.findByPais(siglaPais);
    }

    private static final class CppProxy extends FeriadoRepository
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        public static native ArrayList<Feriado> findAll();

        public static native ArrayList<Feriado> findByPais(String siglaPais);
    }
}
