// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

package com.ezored.holiday;

public final class Pais {


    /*package*/ final String mSigla;

    /*package*/ final String mNome;

    public Pais(
            String sigla,
            String nome) {
        this.mSigla = sigla;
        this.mNome = nome;
    }

    public String getSigla() {
        return mSigla;
    }

    public String getNome() {
        return mNome;
    }

    @Override
    public String toString() {
        return "Pais{" +
                "mSigla=" + mSigla +
                "," + "mNome=" + mNome +
        "}";
    }

}
