// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

package com.ezored.holiday;

public abstract class SincronizacaoListener {
    public abstract void sucesso();

    public abstract void falha(String mensagem);
}
