// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

package com.ezored.holiday;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Sincronizacao {
    public static void baixarTudo(SincronizacaoListener listener)
    {
        CppProxy.baixarTudo(listener);
    }

    private static final class CppProxy extends Sincronizacao
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        public static native void baixarTudo(SincronizacaoListener listener);
    }
}
